In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer, LabelEncoder
import pandas as pd

#### 1. 순서가 없는 범주형 특성 인코딩
* 라이브러리 : sklearn.preprocessing
    * LabelBinarizer : 하나의 클래스 가질 경우
    * MultiLabelBinarizer : 여러개 클래스 가질 경우
    
  
* 라이브러리 : pandas -> 원 핫 인코딩 가능
    * pd.get_dummies(feature[:,0])  : 하나의 클래스 가질 경우 # 하나의 column 활용  

  
* Q1. fit_transform()과 transform()의 차이
    * fit(표준화) -> transform(정규화) 를 순차적으로 시행할 때 사용
        * 표준화 ( fit() ) :  정규분포를 만들게 하기 위해서 𝑥 값에서 평균을 빼고 그 값을 다시 표준편차로 나누어주는 작업을 하는데 이 작업을 하기 위해 평균 𝜇과  표준편차 𝜎를 계산하는 작업이 fit() 
        * 정규화 ( transform() ) : transform()은 정규화 작업을 해주는 것입니다. (𝑥-𝜇)/𝜎 ==> 새로운 𝑥′ 생기는 것이죠
    * fit_transform() 후 transform() 사용함 : 왜냐? 앞서 만들어둔 표준화 결과값(평균, 표준편차)를 그대로 사용하는 것이 transform()이므로
    * 여기서는 표준화를 수행하고 정규화를 진행한 값이 이미 존재했기 때문에 무리없이 사용되었음.  

  
* 유의사항 : 성별을 one-hot encoding할 경우 perfectly negative 한 컬럼 2개가 형성된다. 선형 의존성 발생. -> 컬럼 한개 탈락시켜야 함
* LabelEncoder : 정수 레이블로 변환할 때 # array([2, 0, 2, 1, 2]) : 순서값이 생겨버림
* spare = False : 희소하지 않은 특성 배열을 제작해줌


In [3]:
feature = np.array([['Texas'],
                    ['California'],
                    ['Texas'],
                    ['Delaware'],
                    ['Texas']])

one_hot = LabelBinarizer()
one_hot.fit_transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
# 정수 레이블로 변환
int_hot = LabelEncoder()
int_hot.fit_transform(feature)

/Users/yeonjin/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 2, 1, 2])

In [4]:
one_hot.transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
# 범주형 자료 class 확인
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

In [8]:
# 원핫인코딩 되돌리기 
one_hot.inverse_transform(one_hot.transform(feature))

array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

In [10]:
# pandas로 
pd.get_dummies(feature[:,0])

California  Delaware  Texas
0           0         0      1
1           1         0      0
2           0         0      1
3           0         1      0
4           0         0      1

In [13]:
# 다중 클래스
multiclass_feature = [('Texas', 'Florida'),
                ('California', 'Alabama'),
                ('Texas', 'Florida'),
                ('Delware', 'Florida'),
                ('Texas', 'Alabama')]

In [14]:
one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(multiclass_feature)

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

#### 2. 순서가 있는 범주형 특성 인코딩하기
* 라이브러리 : pandas
    * replace 
    
    
    

In [21]:
df = pd.DataFrame({'Score' : ['Low', 'Low', 'Medium', 'Medium', 'High']})
scale_mapper = {'Low':1,
               'Medium':2,
               'High':3}
df['Score'].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64

In [ ]:
scale_mapper = {'Low':1, 
               'Medium':2,
               'Barely More Than Medium':3,
               'High'}